version: '2'

services:
  drone-server:
    image: rpi-cluster/drone
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SECRET={{ secret }}

  drone-agent:
    image: rpi-cluster/drone
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://{{ master_hostname }}:8000/ws/broker
      - DRONE_SECRET={{ secret }}
